SELECT 
	COLUMN_NAME,
  DATA_TYPE,
  DATA_PRECISION NUMERIC_PRECISION,
  DATA_SCALE NUMERIC_SCALE,
  CHAR_COL_DECL_LENGTH CHARACTER_MAXIMUM_LENGTH,
  CHAR_LENGTH COLUMN_LENGTH,
  
 NULL IS_ROWGUIDCOL,
 NULL IS_IDENTITY,
 NULL IS_COMPUTED
    
FROM
	ALL_TAB_COLUMNS
WHERE TABLE_NAME = '#TableName#' 
ORDER BY column_id