SELECT
	DISTINCT
	USER_CONSTRAINTS.OWNER,
	ALL_TAB_COLUMNS.TABLE_NAME,
    ALL_TAB_COLUMNS.COLUMN_NAME FKCOLUMN_NAME,
    USER_CONSTRAINTS.CONSTRAINT_NAME FK_NAME
FROM
USER_CONSTRAINTS
INNER JOIN ALL_CONS_COLUMNS
	ON USER_CONSTRAINTS.CONSTRAINT_NAME = ALL_CONS_COLUMNS.CONSTRAINT_NAME
INNER JOIN ALL_TAB_COLUMNS
	ON ALL_CONS_COLUMNS.TABLE_NAME = ALL_TAB_COLUMNS.TABLE_NAME
	AND ALL_CONS_COLUMNS.COLUMN_NAME = ALL_TAB_COLUMNS.COLUMN_NAME
WHERE
	ALL_TAB_COLUMNS.OWNER = '#OWNER#'
    AND CONSTRAINT_TYPE = 'R'
    AND ALL_TAB_COLUMNS.TABLE_NAME = '#TableName#'